services:
  dagster-poc:
    container_name: dagster-poc
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        pip install -e .
        dagster-dev
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
