services:
  dagster-data-pipeline:
    container_name: dagster-data-pipeline
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        pip install -e .
        dagster dev -h 0.0.0.0 -p 3000
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
